steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:$SHORT_SHA'
      - '-t'
      - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:latest'
      - '.'
    timeout: 600s

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wecareehr-backend'
      - '--image'
      - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:$SHORT_SHA'
      - '--region'
      - 'africa-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60s'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:$SHORT_SHA'
  - 'africa-south1-docker.pkg.dev/team-ehr/wecareehr-backend/wecareehr-backend:latest'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
